---
# tasks file for roles/lunch_app
# We have this different networks so we can connect the image to our different environments
- name: Launch simple-api container
  docker_container:
  #we manage our container so we know which container we are picking, and telling our machine how many times are we going to restart it
    name: simple-api
    image: isabelatorres/tp-devops-simple-api
    pull: yes
    restart_policy: on-failure
    restart_retries: 3

    env: 
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    networks:
      - name: my-network
      - name: my-second-net