---
# tasks file for roles/lunch_db
- name: Launch PostgreSQL container
  docker_container:
    name: database
    image: isabelatorres/tp-devops-database
    pull: yes
    restart_policy: unless-stopped
    env:
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: my-network