---
# tasks file for roles/create-network, we are creating our first network this is where we are connecting our db and app 
- name: Create Docker network
  docker_network:
    name: my-network
    state: present