#In our playbook er are autmating our function so we tell our machine where to go, which functions to use and the applications use, in which order so it runs correctly
- hosts: all
  gather_facts: true
  become: true

  roles:
    - env_var
    - docker
    - create-network
    - create-second-net
    - launch_db
    - launch_app
    - launch_proxy
